checks:
  exclude:
  - "unset-cpu-requirements"
  - "unset-memory-requirements"
  - "no-read-only-root-fs"
  - "run-as-non-root"
  - "latest-tag"
  - "no-anti-affinity"
  - "non-existent-service-account"
  - "job-ttl-seconds-after-finished"
