apiVersion: monitoring.giantswarm.io/v1alpha1
kind: RemoteWrite
metadata:
  labels:
    application.giantswarm.io/team: atlas
  name: mimir
  namespace: mimir
spec:
  clusterSelector: {}
  remoteWrite:
    name: mimir
    queueConfig:
      capacity: 10000
      maxSamplesPerSend: 1000
      minShards: 10
    tlsConfig:
      insecureSkipVerify: false
    url: http://mimir-gateway.mimir.svc/api/v1/push
