{{- if and .Values.mimir.enabled (index .Values.mimir "metadata-cache" "enabled") }}
{{- include "mimir.lib.verticalPodAutoscaler" (dict "ctx" $ "component" "metadata-cache" "vpa" (index .Values.mimir "metadata-cache" "verticalAutoscaling")) }}
{{- end }}
