{{- if .Values.kedaAutoscaling.querier.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "querier") }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ include "mimir.resourceName" (dict "ctx" . "component" "querier") }}
  {{- if .Values.kedaAutoscaling.querier.horizontalPodAutoscalerConfig }}
  advanced:
    horizontalPodAutoscalerConfig:
      {{- toYaml .Values.kedaAutoscaling.querier.horizontalPodAutoscalerConfig | nindent 6 }}
  {{- end }}
  pollingInterval: {{ .Values.kedaAutoscaling.querier.pollingInterval }}
  cooldownPeriod: {{ .Values.kedaAutoscaling.querier.cooldownPeriod }}
  minReplicaCount: {{ .Values.kedaAutoscaling.querier.minReplicas }}
  maxReplicaCount: {{ .Values.kedaAutoscaling.querier.maxReplicas }}
  triggers:
    {{- toYaml .Values.kedaAutoscaling.querier.triggers | nindent 2 }}
  {{- if .Values.kedaAutoscaling.querier.fallback }}
  fallback:
    {{- toYaml .Values.kedaAutoscaling.querier.fallback | nindent 4 }}
  {{- end }}
{{- end }}
