{{- if and .Values.mimir.enabled (not .Values.enterprise.enabled) -}}
{{- if and .Values.mimir.gateway.enabledNonEnterprise .Values.mimir.gateway.ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "gateway-nginx") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "gateway-nginx") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
  .htpasswd: |
    {{- tpl .Values.mimir.gateway.ingress.basicAuth.htpasswd $ | nindent 4 }}
{{- end -}}
{{- end -}}
