{{- if .Values.routes.gateway.enabled -}}
{{- $route := .Values.routes.gateway }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: {{ $route.kind | default "HTTPRoute" }}
metadata:
  name: {{ $route.name | default (include "mimir.resourceName" (dict "ctx" . "component" "gateway") ) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "gateway") | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- if $route.additionalRules }}
    {{- tpl (toYaml $route.additionalRules) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: {{ .Values.mimir.gateway.service.nameOverride | default (include "mimir.resourceName" (dict "ctx" . "component" "gateway") ) }}
          {{- /* port: {{ $.Values.mimir.gateway.service.port }} */}}
          port: 80
      {{- with $route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- range $name, $policy := $route.securityPolicies }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $policy.name | default (include "mimir.resourceName" (dict "ctx" $ "component" "gateway") ) }}
  labels:
    {{- include "mimir.labels" (dict "ctx" $ "component" "gateway") | nindent 4 }}
    {{- with $policy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $policy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: {{ $route.kind | default "HTTPRoute" }}
      name: {{ $route.name | default (include "mimir.resourceName" (dict "ctx" $ "component" "gateway") ) }}
  {{- toYaml (dict $name $policy) | nindent 2 }}
{{- end }}
{{- end }}
