{{- if .Values.kedaAutoscaling.gateway.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "gateway") }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ include "mimir.resourceName" (dict "ctx" . "component" "gateway") }}
  {{- if .Values.kedaAutoscaling.gateway.horizontalPodAutoscalerConfig }}
  advanced:
    horizontalPodAutoscalerConfig:
      {{- toYaml .Values.kedaAutoscaling.gateway.horizontalPodAutoscalerConfig | nindent 6 }}
  {{- end }}
  pollingInterval: {{ .Values.kedaAutoscaling.gateway.pollingInterval }}
  cooldownPeriod: {{ .Values.kedaAutoscaling.gateway.cooldownPeriod }}
  minReplicaCount: {{ .Values.kedaAutoscaling.gateway.minReplicas }}
  maxReplicaCount: {{ .Values.kedaAutoscaling.gateway.maxReplicas }}
  triggers:
    {{- toYaml .Values.kedaAutoscaling.gateway.triggers | nindent 2 }}
  {{- if .Values.kedaAutoscaling.gateway.fallback }}
  fallback:
    {{- toYaml .Values.kedaAutoscaling.gateway.fallback | nindent 4 }}
  {{- end }}
{{- end }}
