{{- if .Values.mimir.enabled }}
{{- include "mimir.lib.verticalPodAutoscaler" (dict "ctx" $ "component" "ruler" "memberlist" true "targetKind" "Deployment" "vpa" .Values.mimir.ruler.verticalAutoscaling) }}
{{- end }}
