apiVersion: v2
appVersion: 2.12.0
name: mimir
description: A Helm chart for grafana's Mimir
icon: https://s.giantswarm.io/app-icons/grafana-mimir/1/light-icon.svg
home: https://github.com/giantswarm/mimir-app
maintainers:
  - name: giantswarm/team-atlas
    email: team-atlas@giantswarm.io
sources:
  - https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed
dependencies:
  - name: mimir-distributed
    alias: mimir
    version: 5.4.0
    repository: https://grafana.github.io/helm-charts
    condition: mimir.enabled
version: 0.8.1
annotations:
  application.giantswarm.io/team: atlas
