{{- if .Values.mimir.enabled }}
{{- include "mimir.lib.verticalPodAutoscaler" (dict "ctx" $ "component" "store-gateway" "memberlist" true "vpa" .Values.mimir.store_gateway.verticalAutoscaling) }}
{{- end }}
