{{- if .Values.psp.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    app: mimir
  name: mimir-capi
spec:
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - hostPath
  - secret
  - emptyDir
  - projected
  - configMap
  - persistentVolumeClaim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mimir-capi
  labels:
    app: mimir
rules:
  - apiGroups:
      - "extensions"
    resourceNames:
      - mimir-capi
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mimir-capi
  labels:
    app: mimir
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mimir-capi
subjects:
  - kind: ServiceAccount
    name: {{ template "mimir.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
